#!/usr/bin/env bash
# Transfer a file from a client to a server with scp

if [ $# -lt 3 ]; then
	echo "Usage: $0 PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
	exit 1
fi

path_to_file="$1"
server_ip="$2"
username="$3"
path_to_ssh_key="$4"

if [ $# -lt 4 ]; then
	scp -o StrictHostKeyChecking=no "$path_to_file" "$username"@"$server_ip":~/
fi

scp -i "$path_to_ssh_key" "$path_to_file" "$username"@"$server_ip":~/
