#!/usr/bin/env bash
# Configures a NGINX server so that /redirect_me is redirecting to
# another page

apt-get -y update
apt-get -y install nginx
echo "Hello World!" > /var/www/html/index.nginx-debian.html
redirect="\n\tlocation/redirect_me {\n\t\treturn 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;\n\t}\n"
sudo sed -i "53s/.*/$redirect/" /etc/nginx/sites-enabled/default
service nginx start
